zxc/basketapp/urls.py
import basketapp.views as basketapp
from django.urls import path

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.index, name='index'),
    path('add/<int:course_id>/', basketapp.add, name='add'),
    path('remove/<int:course_basket_id>/', basketapp.remove, name='remove'),
]

zxc/zxc/urls.py
import mainapp.views as mainapp
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', mainapp.index, name='index'),
    path('aboutme/', mainapp.aboutme, name='aboutme'),
    path('aboutme/category/<int:pk>/', mainapp.aboutme_page, name='aboutme_page'),
    path('last/', mainapp.last, name='last'),
    path('secretpage/', mainapp.secretpage, name='secret'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('admin/', admin.site.urls),
    path('office/', include('officeapp.urls', namespace='office')),
    path('book/', include('bookapp.urls', namespace='book')),
    path('neoclassica/', include('neoclassicaapp.urls', namespace='neoclassica')),
    path('country/', include('countryapp.urls', namespace='country')),
]
#neoclassicaapp

zxc/basketapp/models.py
from django.contrib.auth.models import User
from django.db import models

from mainapp.models import Course
# Create your models here.
class CourseBasket(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    added = models.DateTimeField(auto_now_add=True)



    def __str__(self):
         return f'{self.added.strftime("%Y.%m.%d %H:%M")} {self.course.name} '

    def to_html(self):
        return f'<i>{self.added.strftime("%Y.%m.%d %H:%M")}</i>: <b>{self.course.name}</b>'

zxc/basketapp/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from basketapp.models import CourseBasket
from mainapp.models import Course




def index(request):
    items = CourseBasket.objects.filter(user=request.user)
    context = {
        'object_list': items,
    }


    return render(request, 'basketapp/last.html', context)


def add(request, course_id):
    course = Course.objects.get(pk=course_id)
    CourseBasket.objects.get_or_create(
        user=request.user,
        # course_id=course_id
        course=course
    )
    # return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    return HttpResponseRedirect(
        reverse('mainapp:catalog_section',
                kwargs={'category_pk': course.category_id})
    )


def remove(request, course_basket_id):
    item = CourseBasket.objects.get(id=course_basket_id)
    item.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

zxc/basketapp/templates/basketapp/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Главная</title>
    {% block css %}
        <link rel="stylesheet" href="\static\css\main.css">
    {% endblock %}
    {% block js %}
    {% endblock %}
</head>
<body>
<div class="main-menu">
    <ul>
        <li>
            <a href="/">Homepage</a>
        </li>
        <li>
            <a href="/aboutme/">About me</a>
        </li>
        <li>
            <a href="/last/">Feedback</a>
        </li>
    </ul>
</div>
{% block content %}
{% endblock %}
</body>
</html>

zxc/basketapp/templates/basketapp/basket.html
{% extends 'mainapp/base.html' %}

{% block content %}
    <h1>this page create in django by <a href="https://vk.com/boostfn">vladlen</a></h1>

    <div class="murder">
        <p><a href="/secretpage/"><img src="\static\css\img\vlad.jpg" width="500px" height="300px"></a></p>
    </div>
    <ul>
        {% for item in object_list %}
            <li>
                {{ item.to_html|safe }}
                <a href="{% url 'basket:remove' item.pk %}">
                    удалить
                </a>
            </li>
        {% endfor %}
    </ul>

{% endblock %}

zxc/basketapp/templates/basketapp/basketapp.html
{% extends 'mainapp/base.html' %}

{% block content %}
    <h1>this page create in django by <a href="https://vk.com/boostfn">vladlen</a></h1>

    <div class="murder">
        <p><a href="/secretpage/"><img src="\static\css\img\vlad.jpg" width="500px" height="300px"></a></p>
    </div>
{% endblock %}

zxc/basketapp/templates/basketapp/last.html
{% extends 'mainapp/base.html' %}

{% block content %}
    <h1>this page create in django by <a href="https://vk.com/boostfn">vladlen</a></h1>

    <div class="murder">
        <p><a href="/secretpage/"><img src="\static\css\img\vlad.jpg" width="500px" height="300px"></a></p>
    </div>
  <a href="{% url 'basket:remove' item.pk %}"

        удалить
    </a>
{% endblock %}