zxc/basketapp/urls.py
import basketapp.views as basketapp
from django.urls import path

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.index, name='index'),
    path('add/<int:course_id>/', basketapp.add, name='add'),
    path('remove/<int:course_basket_id>/', basketapp.remove, name='remove'),
]

zxc/bookapp/urls.py
import bookapp.views as bookapp
from django.urls import path

app_name = 'bookapp'

urlpatterns = [
    path('', bookapp.book, name='book'),
]

zxc/countryapp/urls.py
import countryapp.views as countryapp
from django.urls import path

app_name = 'countryapp'

urlpatterns = [
    path('', countryapp.country, name='country'),
]

zxc/neoclassicaapp/urls.py
import neoclassicaapp.views as neoclassicaapp
from django.urls import path

app_name = 'neoclassicaapp'

urlpatterns = [
    path('', neoclassicaapp.neoclassica, name='neoclassica'),
]

zxc/zxc/urls.py
import mainapp.views as mainapp
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', mainapp.index, name='index'),
    path('aboutme/', mainapp.aboutme, name='aboutme'),
    path('aboutme/category/<int:pk>/', mainapp.aboutme_page, name='aboutme_page'),
    path('last/', mainapp.last, name='last'),
    path('secretpage/', mainapp.secretpage, name='secret'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('admin/', admin.site.urls),
    path('office/', include('officeapp.urls', namespace='office')),
    path('book/', include('bookapp.urls', namespace='book')),
    path('neoclassica/', include('neoclassicaapp.urls', namespace='neoclassica')),
    path('country/', include('countryapp.urls', namespace='country')),
]
#neoclassicaapp

zxc/mainapp/models.py
from django.db import models

class Course(models.Model):
    name = models.CharField(max_length=128)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'курсы'
        verbose_name_plural = 'курс'



class Category(models.Model):
    name = models.CharField(max_length=128)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категорию'
        verbose_name_plural = 'Категории'

class Fantasy(models.Model):
    category = models.ForeignKey(Category,
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=128)
    desc = models.TextField(blank=True)
    release = models.CharField(max_length=128)
    country = models.CharField(max_length=128)
    director = models.CharField(max_length=128)
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Фэнтези'
        verbose_name_plural = 'Фэнтези'


class Shounen(models.Model):
    category = models.ForeignKey(Category,
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=128)
    desc = models.TextField(blank=True)
    release = models.CharField(max_length=128)
    country = models.CharField(max_length=128)
    director = models.CharField(max_length=128)
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Сёнэн'
        verbose_name_plural = 'Сёнэн'

class Cyberpank(models.Model):
    category = models.ForeignKey(Category,
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=128)
    desc = models.TextField(blank=True)
    release = models.CharField(max_length=128)
    country = models.CharField(max_length=128)
    director = models.CharField(max_length=128)
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Киберпанк'
        verbose_name_plural = 'Киберпанк'


class Thriller(models.Model):
    category = models.ForeignKey(Category,
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=128)
    desc = models.TextField(blank=True)
    release = models.CharField(max_length=128)
    country = models.CharField(max_length=128)
    director = models.CharField(max_length=128)
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Боевик'
        verbose_name_plural = 'Боевик'

zxc/mainapp/views.py
from django.shortcuts import render


from mainapp.models import Category, Fantasy, Course



def index(request):
    return render(request, 'mainapp/index.html')


def aboutme(request):
    categories = Category.objects.all()
    context = {
        'categories': categories,
    }
    return render(request, 'mainapp/aboutme.html', context)


def last(request, pk):
    course = Course.objects.fliter(course_id=pk)
    context = {
       'course': course,
        'page_title':'страница каталога'
    }
    return render(request, 'mainapp/last.html', context)


def secretpage(request):
    return render(request, 'mainapp/secretpage.html')

def aboutme_page(request, pk):
    course = Category.objects.filter(category_id=pk)
    context = {
        'Fantasy': Fantasy,
        'page_title': 'страница каталога'
    }
    return render(request, 'mainapp/aboutme_page.html', context)

zxc/mainapp/templates/mainapp/aboutme.html
{% extends 'mainapp/base.html' %}

{% block content %}
    <h1>about me</h1>

    <h2>im student kpk, live in Russia, Kurgan.....bla bla bla ... ... ... bla bla bla bla ...</h2>

    <div class="catelog-menu">
        {% for item in categories %}
            <ul>
                <li>
                    <a href="{% url 'aboutme_page' item.pk %}"> {{ item }} </a>

                </li>
            </ul>
        {% endfor %}
    </div>

{% endblock %}

zxc/mainapp/templates/mainapp/aboutme_page.html
{% extends 'mainapp/base.html' %}

{% block content %}
    <h1>about me</h1>

    <h2>im student kpk, live in Russia, Kurgan.....bla bla bla ... ... ... bla bla bla bla ...</h2>

    <div class="courses-menu">
        {% for item in courses %}
            <ul>
                <li>
                    <a href="{% url 'aboutme' item.pk %}">
{#                    <a href="#"> {{ item }} </a>#}
                </li>
            </ul>
            <a href="{% url 'basket:add' course_id %}">
                Записаться
            </a>
        {% endfor %}
    </div>

{% endblock %}

zxc/mainapp/templates/mainapp/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Главная</title>
    {% block css %}
        <link rel="stylesheet" href="\static\css\main.css">
    {% endblock %}
    {% block js %}
    {% endblock %}
</head>
<body>
<div class="main-menu">
    <ul>
        <li>
            <a href="/">Homepage</a>
        </li>
        <li>
            <a href="/aboutme/">About me</a>
        </li>
        <li>
            <a href="/last/">Feedback</a>
        </li>
        <li>
                    <a href="{% url 'office:office' %}">Оффисы</a>
                    <a href="{% url 'book:book' %}">Книги</a>
                    <a href="{% url 'neoclassica:neoclassica' %}">Неоклассика</a>
                    <a href="{% url 'country:country' %}">Страны</a>
        </li>
    </ul>
</div>
{% block content %}
{% endblock %}
</body>
</html>

zxc/mainapp/templates/mainapp/secretpage.html
{% extends 'mainapp/base.html' %}

{% block content %}
    <h1>ЛУЧШЕ ВАМ СЮДА НЕ ЗАХОДИТЬ! ЭТО ПОТАЙНАЯ СТРАНИЦА!</h1>
<div class="vlad">
<img src="\static\css\img\cat.jpg" alt="welcome" class="vlad">
</div>
<a
{% endblock %}